project:
  type: website

website:
  title: "David Ajowi"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/daaj
      - icon: linkedin
        href: https://linkedin.com/in/davidajowi
      - icon: github
        href: https://github.com/ajowi
  twitter-card: true
  open-graph: true
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto



