project:
  type: website

website:
  title: "David Ajowi"
  navbar:
    title: false
    background: light
    logo: "alogo-transparent.png"
    logo-alt: "David Ajowi"
    right:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - icon: twitter-x
        href: https://x.com/daaj
      - icon: linkedin
        href: https://linkedin.com/in/davidajowi
      - icon: github
        href: https://github.com/ajowi
  bread-crumbs: true
  twitter-card: true
  open-graph: true
  site-url: https://davidajowi.com
  repo-url: https://github.com/ajowi/ajowi.github.io
  favicon: "favicon.ico"
  image: "daaj.jpeg"
  page-footer: 
    center: "Copyright &copy; 2024, David Ajowi"
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto



